### ISSUE TITLE
Cannot be used in rust 2024

### ISSUE THREAD

**Issue by limuy2022** [Evian-Zhang/static-keys#5]
Taking a reference to a [static mut](https://doc.rust-lang.org/nightly/reference/items/static-items.html#mutable-statics) is no longer allowed.

Please check [Rust2024 static mut](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html). This will prevent user from using this crate in the future.

**Comment by Evian-Zhang** [comment]
Thank you for your report. I will fix it as soon as possible.
